language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: UEyDj0mhhOb9xDsoYy7jLgzYJnZ9jhh6KzxiCEcZ7U2sGchG/1y6iszHyN2W9wiZNLuM12hb9Ar8GZyF3WiU8m1SSf6hpQN1V3jYwunuuhZEkrh8S6i3GP096E/s/pSOFuC2hax+Lz/5HRmYUz9CVTYrOZQt927fRhKFQEEAxpJSxU3ENrvjQOzYI+9He5JiAhS7go7HKz3CRwtmL4uJwXhYVgUAPpvi4liRb1wTisK5HWlxMl77re7jpHFztzm0s4iVRASXNxkFxEVkEGaq03GIPRUxYxb7k+iQX1wg0fOieYQyF2uT0C80qXTCk9unyF2XZRSZxahPcyPV39WcHdnn2PP5ZyhkLzJIib04AhXRqJhqK1YcZiqq3YSKJVPEcM2lp88JC5bMYvivEr+XnPXBO05C8+6A979Y/BqrY5+OQr3P19hzYh8L6w+V0HJkWbpZ5C7r2v727UWT3EOsvKpIMA8HEFcarpSZH0zrDeXP5td8+SASIFo6cdIJxQxEfCvBmOYWKtPqMuN2oAjOKVEK0Wk4kQtdXAc4Mt5Hop4FF/MUU4Qc3BYQ7NBahyDhVvQx20KnCucETAGQ6i5bWCoy7urLjpBXxwG9jRLFT7w6PgijS8dsomUHinzZH0PwPZOgYniwh4fSS9CrZMKm2kjRwQziztEJSS5/5Lq9ZGw=
  file: build/libs/xld-duckcreek-plugin-1.0.0-beta.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-duckcreek-plugin
